### ISSUE TITLE
Colors hardcoded to blue

### ISSUE THREAD

**Issue by AliAkolade** [Theblockbuster1/spicetify-extensions#11]
I currently use a dynamic spicetify theme that changes color according to the album art, but this extension keeps changing the colors to blue and white.

**Comment by Theblockbuster1** [comment]
Which theme are you using? I assume there may be some conflict with the custom property `--cover-color`. I may change it to something more specific in the next update.

**Comment by Theblockbuster1** [comment]
May be fixed by 394b523, let me know.

**Comment by Theblockbuster1** [comment]
Feel free to reopen if anything reoccurs

**Comment by AliAkolade** [comment]
Works now. Thanks.

> May be fixed by [394b523](https://github.com/Theblockbuster1/spicetify-extensions/commit/394b523cf5192c3c93b799a34240e2baa8251a1c), let me know.
