### ISSUE TITLE
Cover ambience song transition

### ISSUE THREAD

**Issue by jazzathedev** [Theblockbuster1/spicetify-extensions#13]
I like visually how the cover ambience looks, it matches quite well with my current theme, but could you make it smoothly transition from one prominent colour to the next when changing song, instead of doing it suddenly shortly after changing song? I know nothing about how spicetify extensions are made but I think this isn't too unreasonable to ask for? I'm imagining just a simple fade between the two colours, not entirely sure if there's certain ways of fading between them that work better than others? (I'm thinking fading between say...green and red could look weird?)
Other than that one thing, it looks really good and I'm glad you made it :D

**Comment by Theblockbuster1** [comment]
Fixed by #12 :-)
