### ISSUE TITLE
Library X support?

### ISSUE THREAD

**Issue by thegoldknight** [Theblockbuster1/spicetify-extensions#22]
Cover Ambience is not aligned with the side with the experimental feature Library X turned on. 

<img width="351" alt="image" src="https://github.com/Theblockbuster1/spicetify-extensions/assets/135397968/2c3ee040-e7d8-4331-bf06-c78e1cade2c5">

It works fine without Library X. 

<img width="344" alt="Screenshot 2023-06-03 at 11 56 08 AM" src="https://github.com/Theblockbuster1/spicetify-extensions/assets/135397968/89aed52a-bca6-4362-ba25-5ac65aba51c5">

Is there a way to make it aligned with Library X on?

**Comment by Theblockbuster1** [comment]
Does this still happen? I can't reproduce this, I haven't really used Library X much myself.

**Comment by Theblockbuster1** [comment]
Never mind, I got it. It seems to be in incompatibility between Library X's sidebar ~~, the Comfy theme,~~ and Cover Ambience.

Edit: Actually, the color mismatch from other themes make it more obvious, but it happens even with the default theme.
