### ISSUE TITLE
Suggestion: Queue color change

### ISSUE THREAD

**Issue by thegoldknight** [Theblockbuster1/spicetify-extensions#23]
Would it be possible to have the queue time text color change with the theme?
<img width="1049" alt="Screenshot 2023-06-06 at 6 07 34 PM" src="https://github.com/Theblockbuster1/spicetify-extensions/assets/135397968/b58586f9-75a6-4b03-928e-a0e389e0985d">

**Comment by Theblockbuster1** [comment]
Yes, now the colour should match the current theme!
