### ISSUE TITLE
Cover ambience not changing 

### ISSUE THREAD

**Issue by thegoldknight** [Theblockbuster1/spicetify-extensions#24]
The cover ambience just stays the same color of the first song and never changes.

**Comment by Theblockbuster1** [comment]
I can't reproduce, which Spotify version are you on? I'm on 1.2.14.1149

**Comment by DominikDoom** [comment]
I can confirm that it doesn't work for me as well.

Likely cause:
https://github.com/Theblockbuster1/spicetify-extensions/blob/main/CoverAmbience/CoverAmbience.js#L153-L155C9

Here the `Spicetify.Player.addEventListener('songchange', setGradient);` is only attached in the observer block, but not if the page was already ready and found the main-nowPlayingBar-container first try. In that case it will only call it once. 
It works as expected after I attached the event listener manually in the dev tools console.

So I guess the reason it doesn't happen to you is just a race condition, on your client the extension seems to run a bit earlier, so the page isn't ready yet and the observer part runs.

**Comment by Theblockbuster1** [comment]
Oh, that's probably because I'm running the extension locally rather than via Spicetify Marketplace. I'll try fixing

**Comment by Theblockbuster1** [comment]
Let me know if that's good :)
