### ISSUE TITLE
cover ambience only works every other song

### ISSUE THREAD

**Issue by eyitzanthony** [Theblockbuster1/spicetify-extensions#26]
the cover ambience only works for every other song on my spotify. is this supposed to happen, and if so is there any way to make it so it works every song?

**Comment by Theblockbuster1** [comment]
Are you using any themes?

**Comment by anthonymvaygen** [comment]
Yes, I'm using the Galaxy theme by harbassan. Is there a way I can use it without the issue happening?

**Comment by Theblockbuster1** [comment]
That should fix it :-)

**Comment by anthonymvaygen** [comment]
Thank you!
