### ISSUE TITLE
Sleep Timer button is not functional

### ISSUE THREAD

**Issue by jetdzhet** [Theblockbuster1/spicetify-extensions#32]
Sleep Timer extension has the button (sometimes without the icon though), but when I set it to stop playback after 1 song, it doesn't end up stopping it,

**Comment by Skellingtor** [comment]
Can confirm the issue is still present.

Spotify for Windows (64 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.23.2

**Comment by Theblockbuster1** [comment]
I'm unsure what causes this, it also seems to happen in the [other sleep timer extension by ohitstom](https://github.com/ohitstom/spicetify-extensions/tree/main/sleepTimer)...

**Comment by jetdzhet** [comment]
I think the extension actually tries to pause the song, but a split second latear the song keeps on going anyway.

**Comment by Theblockbuster1** [comment]
I've had an idea for a workaround which I haven't yet found the time to implement. The extension could mute the music while it attempts to pause the song, so if the song replays itself, it shouldn't interfere... I suppose it would also require the extension to remember the timestamp of where it was supposed to pause, and when the process is done, jump back to that song position.

**Comment by Skellingtor** [comment]
Good news: the extension seems to be working again!

Bad news: can't see the sleep timer button, but it's clickable on the bottom bar
![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/19526287/12f9a8d5-d895-4b83-ac20-d7e1970db838)

**Comment by Theblockbuster1** [comment]
I fixed the class so the icon should show now. Also it seems like Spotify might've fixed the bug that prevents pausing songs at the beginning, nice!

**Comment by jetdzhet** [comment]
Welp, Spotify just updated, and that update broke the extension again

**Comment by jetdzhet** [comment]
Welp, the new Spotify update (Spotify for Windows (64 bit) - 1.2.26.1187.g36b715a1) seems to have broken the extension again.
