### ISSUE TITLE
[Design Discussion] SleepTimer

### ISSUE THREAD

**Issue by brusvv** [Theblockbuster1/spicetify-extensions#37]
I'm not a designer, but I decided to suggest reducing the size of the extension. Here is my concept or sketch.
![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/55412131/6b6d51b2-5f7e-4a80-86b2-ef5911ba8286)

My idea is not perfect in detail, but I think this way the extension would look better, it would not be overloaded with information and would not take up unnecessary space.

Also I've few ideas about fonts.

**Comment by Theblockbuster1** [comment]
Yeah, I agree that compacting the menu would look better! I might try that. What ideas do you have about fonts?

**Comment by brusvv** [comment]
I think need some kind of bold font, and make the text on the start button a little bigger, more like the names of artists in the artist cards.

It would also be nice to reduce the size of the enabled timer window, maybe add a stop sign icon next to it. Because changing the active timer is useless. By the way, what about the pause button?

![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/55412131/8bf9d454-4245-439d-9711-03f69486510c)
My example doesn’t look very good, for example, the logo could be made a little larger, but I think the concept is clear.

Is it possible to replace the extension button while the timer is active? For example, the number of songs and the note icon and the remaining minutes.

**Comment by Theblockbuster1** [comment]
![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/48650812/39efe495-59e6-4aa1-aaed-350575260e3a)
![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/48650812/32cc2b98-654d-4c32-882e-6608eacd42fd)

Here I implemented some of your ideas, it's unfinished at the moment, but it is close. I think I'll make the number picker inputs look thinner, and maybe the icons could use improvement. Maybe I should also change the "Start Timer" text to just "Start", or just put a little play icon? 🤔 I like the idea of making it simple and easier on the eye, without overdoing it though.

**Comment by Theblockbuster1** [comment]
Let me know what you think :)
I closed the issue, but the design is still open for discussion 👍
