### ISSUE TITLE
Can't see Queue time (queue time extension)

### ISSUE THREAD

**Issue by kuroigg** [Theblockbuster1/spicetify-extensions#38]
The queue time extension doesn't display time. This issue is present from marketplace v1.0.1.

https://github.com/Theblockbuster1/spicetify-extensions/assets/142319924/990c8d93-7be6-4fa9-988c-da2b4def80d9

**Comment by Theblockbuster1** [comment]
Hi, what version of spotify + spicetify are you on?

**Comment by kuroigg** [comment]
I am using:
Spotify for Windows (64 bit) v1.2.37.701.ge66eb7bc
Spicetify v2.36.11

**Comment by Theblockbuster1** [comment]
Oh, I seem to be on the exact same version.. what theme are you using?

**Comment by Theblockbuster1** [comment]
It works fine for me, I don't usually use themes though

**Comment by Theblockbuster1** [comment]
Ohh... 
![image](https://github.com/Theblockbuster1/spicetify-extensions/assets/48650812/316d7977-6a35-4c56-86e3-29d2b8a01c4e)
I had this experimental feature on. I'll update it now.

**Comment by kuroigg** [comment]
Theme: Default / Ocean
I have tried two other themes, it doesn't work on them either. (the text theme, and one punch man theme) Same with default theme.

**Comment by Theblockbuster1** [comment]
should be fixed in the latest update :)
if you're using the marketplace it may take a few hours to update automatically
