### ISSUE TITLE
Sleep Timer Not Working As Intended

### ISSUE THREAD

**Issue by JayTheXXVII** [Theblockbuster1/spicetify-extensions#4]
![9b5db8ea580d76611f91b609cc5d06ce](https://user-images.githubusercontent.com/34871492/201541362-22b7a54c-6b36-42e0-99ed-fc8e9919d492.png)

Seems like Sleep Timer isnt working as intended, I updated Spotify & reapplied Spicetify and Sleep Timer seems to be one of the only extensions I am having issues with.

**Comment by Theblockbuster1** [comment]
The newest Spotify update seemed to have removed some CSS that the extension relied on, but I added it back in the next update which will fix this.
