### ISSUE TITLE
[Bug] Not showing the queue time

### ISSUE THREAD

**Issue by sergiorgiraldo** [Theblockbuster1/spicetify-extensions#6]
The text was not showing. I managed to fix changing the selector.

From: Type__TypeElement-goli3j-0
To: **DG9CsoFIptJhAneKoo_F**

**Comment by Theblockbuster1** [comment]
Thank you, Spotify keep changing their class names. Fixed in https://github.com/Theblockbuster1/spicetify-extensions/commit/1417adb5afc246e36c1efd1d29abe845dd1d3a26.
