### ISSUE TITLE
SleepTime Icon not showing

### ISSUE THREAD

**Issue by mephisto3478** [Theblockbuster1/spicetify-extensions#7]
Hey,
first of all thank you for your efforts!
Unfortunately, the icon for using the SleepTime Extension does not show up in my Spotify client (Version 1:1.1.84.716-3 on Arch Linux).
Because of an update, the extension is possibly not working anymore.

**Comment by Theblockbuster1** [comment]
Very kind of you! It seems that the latest of version on Linux is more behind than the Windows version (I'm on 1.2.0.1165). Assuming that you are using [snap](https://snapcraft.io/spotify), you may be able to update to version 1.1.99.878 with `sudo snap install spotify --candidate`, but unfortunately it may still not work as it is not on Spotify version v1.2. Let me know if you manage to update to a compatible version.

**Comment by mephisto3478** [comment]
Actually I've got the aur package installed, which seems to be out of date. I will try to install spotify with snap later and report back to you. Thanks for your recommendation!

**Comment by Theblockbuster1** [comment]
It seems that the same package on AUR is called [spotify-edge](https://aur.archlinux.org/packages/spotify-edge). No problem by the way!

**Comment by mephisto3478** [comment]
Now it's working perfectly fine :) Thank you!
